### ISSUE TITLE
docs update

### ISSUE THREAD

**Issue by ParallelUniv3rse** [atomicpages/gulp-download2#2]
Trying to download multiple json files and set their names like so: 
```
    [{
        url: config.getTranslationApiUrl("en"),
        name: 'en.json',
    },{
        url: config.getTranslationApiUrl("de"),
        name: 'de.json',
    }]
```
failed with an error `Error: No path specified! Can not get relative.`

Looking into the source code if found that updating the array to 
```
    [{
        url: config.getTranslationApiUrl("en"),
        file: 'en.json',
    },{
        url: config.getTranslationApiUrl("de"),
        file: 'de.json',
    }]
```
solves the issue. I suggeest updating the readme.

**Comment by atomicpages** [comment]
@ParallelUniv3rse sure. Thanks!

**Comment by jsve** [comment]
This is still not fixed on npm.
